#!/bin/bash
. test/integration/helper

#
# postgres
#

test_dbu_conn_connects_to_postgres () {
printf "select version();" | dbu conn | grep -q "PostgreSQL"
}

test_dbu_conn_streams_from_postgres () {
printf "select 1,'a'" | dbu conn | assert_output "\
1	a
"
}

test_dbu_conn_streams_from_postgres_with_headers () {
printf "select 1 as key, 'a' as value" | dbu conn -H | assert_output "\
key	value
1	a
"
}

#
# -p
#

test_dbu_conn_p_prints_preview_command_for_postgres () {
dbu conn -p | grep -q "psql -h"
}

. ts
