#!/usr/bin/env ruby
begin
  require 'dbu'
  require 'shellwords'

  options = Dbu.options(
    :mode => :exec,
    :opts => [],
    :field_sep => "\t",
    :stream => !$stdin.tty?
  )
  OptionParser.new do |opts|
    opts.banner = %{
usage: dbu conn [options] -- [ARGS...]

  Connect to specified database using the dbu config file and provide the user
  a prompt. If stdin is not a tty then the connection will accept sql and
  format the output as a stream (ie no table decorations and non-result
  output).

options:
}.lstrip

    opts.on("-c", "--config-file CONFIG_FILE", "database config file (#{options[:config_file]})") do |value|
      options[:config_file] = value
    end

    opts.on("--debug", "enable debugging") do
      $DEBUG = true
    end

    opts.on("-e", "--environment ENVIRONMENT", "database environment (#{options[:environment]})") do |value|
      options[:environment] = value
    end

    opts.on("-F", "--field-sep FIELD_SEP", "field separator for -s (#{options[:field_sep].inspect})") do |value|
      options[:field_sep] = value
    end

    opts.on("-H", "--[no-]headers", "print headers") do |value|
      options[:headers] = value
    end

    opts.on("-h", "--help", "print this help") do
      puts opts
      puts
      puts Dbu.version
      exit
    end

    opts.on("-i", "--irb", "start an irb session with connection") do
      options[:mode] = :irb
    end

    opts.on("-p", "--preview", "preview command") do
      options[:mode] = :preview
    end

    opts.on("-s", "--[no-]stream", "stream results") do |value|
      options[:stream] = value
    end

    opts.on("-v", "--verbose", "verbose output") do
      options[:level] -= 1
    end

    opts.on("--version", "print version information") do |node|
      puts Dbu.version
      exit
    end
  end.parse!
  Dbu.setup(options)

  config  = Dbu.init_config(options)
  adapter = config.adapter

  args = adapter.command_args(options)
  env  = adapter.command_env

  command = Shellwords.shelljoin(args.map(&:to_s) + ARGV)

  case options[:mode]
  when :preview
    puts command
  when :irb
    require 'irb'
    def adapter; @adapter; end
    def adapter=(value); @adapter = value; end
    self.adapter = adapter
    IRB.start
  else
    env.each_pair do |key, value|
      ENV[key] = value
    end
    exec command
  end

rescue Interrupt
  exit 130
rescue Errno::EPIPE
  exit 0
rescue
  raise if $DEBUG
  $stderr.puts $!.message
  exit 1
end
