#!/bin/bash
#############################################################################
dbu_db_usage () {
printf "%s" "\
usage: dbu db [-h] COMMAND ...

  Launches db commands.

options:

  -h          prints help

tables:

`prototype-list db | sed -e 's/^/  /'`

"
}
while getopts "h" option
do
  case $option in
    (h)  dbu_db_usage
         exit 0 ;;
    (*)  dbu_db_usage | head -n 1
         exit 2 ;;
  esac
done
shift $(($OPTIND - 1))

if [ $# -eq 0 ]
then
  dbu_db_usage
  exit 1
fi
#############################################################################
prototype_exec "$@"
