#!/bin/bash
. test/integration/helper

#
# -c
#

test_dbu_conn_c_sets_config_file () {
config_file="$ts_test_dir/config"
mkdir -p "$ts_test_dir"
sed -e 's/development/example/' config/database.yml > "$config_file"
dbu conn -p -c "$config_file" -e example | grep -q "psql -h"
}

#
# -h
#

test_dbu_conn_prints_help () {
dbu conn -h | grep -q "usage: dbu conn"
}

. ts
