#!/bin/bash
. test/integration/helper

test_dbu_console_connects_to_postgres () {
export DBU_ENVIRONMENT=postgres
printf "select version();" | dbu console | grep -q "PostgreSQL"
}

#
# -h
#

test_dbu_console_prints_help () {
dbu console -h | grep -q "usage: dbu console"
}

#
# -p
#

test_dbu_console_p_prints_preview_command () {
export DBU_ENVIRONMENT=postgres
dbu console -p | grep -q "psql -h"
}

. ts
