#!/bin/bash
. test/integration/helper

setup () {
config_exe="$ts_test_dir/config"
config_file="$ts_test_dir/config.yml"
sql_dir="$ts_test_dir/sql"
mkdir -p "$sql_dir"
}

#
# usage
#

test_dbu_db_setup_prints_sql_files_in_order () {
printf "a\n" > "$sql_dir/a"
printf "b\n" > "$sql_dir/b"
dbu db setup "$ts_test_dir" | assert_output "\
a
b
"
}

test_dbu_db_setup_evaluates_sql_files_as_erb_with_configs_in_scope () {
cat > "$config_file" <<DOC
key: value
DOC

cat > "$sql_dir/a" <<DOC
key <%= key %>
DOC

dbu db setup "$ts_test_dir" | assert_output "\
key value
"
}

test_dbu_db_setup_processes_config_file_with_config_file_exe_if_present () {
cat > "$config_file" <<DOC
key: value
DOC

cat > "$config_exe" <<DOC
#!/bin/bash
sed -e 's/value/VALUE/'
DOC
chmod +x "$config_exe"

cat > "$sql_dir/a" <<DOC
key <%= key %>
DOC

dbu db setup "$ts_test_dir" | assert_output "\
key VALUE
"
}

#
# -h
#

test_dbu_db_setup_prints_help () {
dbu db setup -h | grep -q "usage: dbu db setup"
}

#
# -z
#

test_dbu_db_setup_only_prints_files_newer_than_z () {
printf "a\n" > "$sql_dir/a"
printf "b\n" > "$sql_dir/b"
printf "c\n" > "$sql_dir/c"

touch -t "$(date -r 1 "+%Y%m%d%H%M.%S")" "$sql_dir/a"
touch -t "$(date -r 2 "+%Y%m%d%H%M.%S")" "$sql_dir/b"
touch -t "$(date -r 3 "+%Y%m%d%H%M.%S")" "$sql_dir/c"

dbu db setup -z "$(date -r 1 "+%Y-%m-%d %H:%M:%S")" "$ts_test_dir" | assert_output "\
b
c
"
}

test_dbu_db_setup_z_accepts_reference_file () {
printf "a\n" > "$sql_dir/a"
printf "b\n" > "$sql_dir/b"
printf "c\n" > "$sql_dir/c"

touch -t "$(date -r 1 "+%Y%m%d%H%M.%S")" "$sql_dir/a"
touch -t "$(date -r 2 "+%Y%m%d%H%M.%S")" "$sql_dir/b"
touch -t "$(date -r 3 "+%Y%m%d%H%M.%S")" "$sql_dir/c"
touch -t "$(date -r 1 "+%Y%m%d%H%M.%S")" "$sql_dir/d"

dbu db setup -z "$sql_dir/d" "$ts_test_dir" | assert_output "\
b
c
"
}

. ts
