#!/bin/bash
. test/integration/helper

test_dbu_db_init_copies_prototype_to_dir () {
dbu db init "$ts_test_dir"
find "$ts_test_dir" -type f | assert_output "\
$ts_test_dir/config
$ts_test_dir/config.yml
$ts_test_dir/sql/00_example.sql
"
}

test_dbu_db_init_does_nothing_if_dir_exists () {
mkdir -p "$ts_test_dir"
touch "$ts_test_dir/file"
dbu db init "$ts_test_dir"
[ -e "$ts_test_dir/file" ] && [ ! -e "$ts_test_dir/config" ]
}

#
# -f
#

test_dbu_db_init_f_removes_existing_dir () {
mkdir -p "$ts_test_dir"
touch "$ts_test_dir/file"
dbu db init -f "$ts_test_dir"
[ ! -e "$ts_test_dir/file" ] && [ -e "$ts_test_dir/config" ]
}

#
# -p
#

test_dbu_db_init_p_sets_prototype_dir () {
mkdir -p "$ts_test_dir/a/sql"
printf "a: b\n" > "$ts_test_dir/a/config.yml"
printf "select * from table;\n" > "$ts_test_dir/a/sql/00.sql"

dbu db init -p "$ts_test_dir/a" "$ts_test_dir/b"
cat "$ts_test_dir/b/config.yml" "$ts_test_dir/b/sql/00.sql" | assert_output "\
a: b
select * from table;
"
}

#
# -l
#

test_dbu_db_init_l_symlinks_config_and_sql_into_dir () {
dbu db init -l "$ts_test_dir"
cat <(find "$ts_test_dir" -type f) <(echo ---) <(find "$ts_test_dir" -type l) | assert_output "\
$ts_test_dir/config.yml
---
$ts_test_dir/config
$ts_test_dir/sql
"
}

#
# -h
#

test_dbu_db_init_prints_help () {
dbu db init -h | grep -q "usage: dbu db init"
}

. ts
