#!/bin/bash
. test/integration/helper

setup () {
config_exe="$ts_test_dir/config"
config_file="$ts_test_dir/config.yml"
mkdir -p "$ts_test_dir"
}

#
# usage
#

test_dbu_setup_prints_sql_files_in_lexical_order () {
printf "a\n" > "$ts_test_dir/a.sql"
printf "b\n" > "$ts_test_dir/b.sql"
dbu setup "$ts_test_dir" | assert_output "\
a
b
"
}

test_dbu_setup_evaluates_sql_files_as_erb_with_configs_in_scope () {
cat > "$config_file" <<DOC
key: value
DOC

cat > "$ts_test_dir/a.sql" <<DOC
key <%= key %>
DOC

dbu setup "$ts_test_dir" | assert_output "\
key value
"
}

test_dbu_setup_processes_config_file_with_config_file_exe_if_present () {
cat > "$config_file" <<DOC
key: value
DOC

cat > "$config_exe" <<DOC
#!/bin/bash
sed -e 's/value/VALUE/'
DOC
chmod +x "$config_exe"

cat > "$ts_test_dir/a.sql" <<DOC
key <%= key %>
DOC

dbu setup "$ts_test_dir" | assert_output "\
key VALUE
"
}

#
# -h
#

test_dbu_setup_prints_help () {
dbu setup -h | grep -q "usage: dbu setup"
}

#
# -z
#

test_dbu_setup_prints_all_files_lexically_after_out_of_date_file () {
printf "a\n" > "$ts_test_dir/a.sql"
printf "b\n" > "$ts_test_dir/b.sql"
printf "c\n" > "$ts_test_dir/c.sql"

touch -t "$(date -r 1 "+%Y%m%d%H%M.%S")" "$ts_test_dir/a.sql"
touch -t "$(date -r 2 "+%Y%m%d%H%M.%S")" "$ts_test_dir/b.sql"
touch -t "$(date -r 1 "+%Y%m%d%H%M.%S")" "$ts_test_dir/c.sql"

dbu setup -z "$(date -r 1 "+%Y-%m-%d %H:%M:%S")" "$ts_test_dir" | assert_output "\
b
c
"
}

test_dbu_setup_z_accepts_reference_file () {
printf "a\n" > "$ts_test_dir/a.sql"
printf "b\n" > "$ts_test_dir/b.sql"
printf "c\n" > "$ts_test_dir/c.sql"

touch -t "$(date -r 1 "+%Y%m%d%H%M.%S")" "$ts_test_dir/a.sql"
touch -t "$(date -r 2 "+%Y%m%d%H%M.%S")" "$ts_test_dir/b.sql"
touch -t "$(date -r 3 "+%Y%m%d%H%M.%S")" "$ts_test_dir/c.sql"
touch -t "$(date -r 1 "+%Y%m%d%H%M.%S")" "$ts_test_dir/d"

dbu setup -z "$ts_test_dir/d" "$ts_test_dir" | assert_output "\
b
c
"
}

test_dbu_setup_z_builds_all_for_non_existant_file () {
printf "a\n" > "$ts_test_dir/a.sql"
printf "b\n" > "$ts_test_dir/b.sql"
printf "c\n" > "$ts_test_dir/c.sql"

touch -t "$(date -r 1 "+%Y%m%d%H%M.%S")" "$ts_test_dir/a.sql"
touch -t "$(date -r 2 "+%Y%m%d%H%M.%S")" "$ts_test_dir/b.sql"
touch -t "$(date -r 3 "+%Y%m%d%H%M.%S")" "$ts_test_dir/c.sql"

dbu setup -z "$ts_test_dir/d" "$ts_test_dir" | assert_output "\
a
b
c
"
}

. ts
